src/main/java/reagents/app/kit/bean/KitBean.java
package reagents.app.kit.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;

import javax.faces.application.FacesMessage;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;
import reagents.app.exception.DbIOException;
import reagents.app.exception.LoginExpiredExeption;
import reagents.app.kit.KitFunctions;
import reagents.app.login.bean.LoginBean;
import reagents.app.view.DataView;
import reagents.app.Msg;
import reagents.data.kit.*;
import reagents.data.settings.DiscardOptionsDAO;

@SessionScoped
@Named
public class KitBean implements Serializable {

	private static final long serialVersionUID = 1L;
	/* ------------------------------------------------------------------------- */
	private DataView<Kit> view;
	public DataView<Kit> getView() {
		return view;
	}
	/* ------------------------------------------------------------------------- */
	/* Add Kits Variables */
	private List<KitsAdd> add;
	public List<KitsAdd> getKitAdd() {
		return add;
	}
	/* ------------------------------------------------------------------------- */
	/* Variable LoginBean for access name of logged user. */
	private LoginBean loginBean;
	/* ------------------------------------------------------------------------- */
	private ResourceBundle cz;
	private String userName;
	private KitFunctions func;
	DiscardOptionsDAO discardOptionsDAO;
	/* ------------------------------------------------------------------------- */
	public void init() throws LoginExpiredExeption, DbIOException {
		if(userName==null) {
			userName = loginBean.getLoggedUserName();
		}
		if(view == null){
			view = new DataView<>(new Kit(),userName);
		}
		if(func==null){
			func = new KitFunctions(userName);
		}
		view.initCurrent();
		if(cz == null){
			cz = loginBean.getCz();
		}
	}
	/* ------------------------------------------------------------------------- */
	@Inject
	public KitBean (LoginBean loginBean) throws LoginExpiredExeption, DbIOException {
		this.loginBean = loginBean;
		discardOptionsDAO = new DiscardOptionsDAO();
		init();
	}
	/* ------------------------------------------------------------------------- */
	private boolean showConsumed=false;
	public boolean isShowConsumed() {
		return showConsumed;
	}
	/* ------------------------------------------------------------------------- */
	private String editable;
	public String getEditable() {
		return editable;
	}
	/* ------------------------------------------------------------------------- */
	public String editNext() {
		editable = "false";
		Msg.create(cz.getString("info"),cz.getString("checkIt"),FacesMessage.SEVERITY_INFO,false);
		RequestContext.getCurrentInstance().update("kitEdit:table");
		return "";
	}
	/* ------------------------------------------------------------------------- */
	public String editPrev() {
		editable = "true";
		Msg.create(cz.getString("info"),cz.getString("fillIt"),FacesMessage.SEVERITY_INFO,false);
		RequestContext.getCurrentInstance().update("kitEdit:table");
		return "edit?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */
	public String edit() {
		if(view.getSelected().size()==0) {
			Msg.create(cz.getString("warning"), cz.getString("youMustSelectSomething"), FacesMessage.SEVERITY_WARN, false);
			return "";
		}
		view.reload();
		String result = func.checkIfLocked(view.getEdited());
		if (!result.equals("No")) {
			Msg.create(cz.getString("error"),cz.getString("isLockedBy")+" "+result+".",FacesMessage.SEVERITY_WARN,false);
			return "";
		}
		view.lock();
		editable = "true";
		Msg.create(cz.getString("info"),cz.getString("fillIt"),FacesMessage.SEVERITY_INFO,true);
		return "edit?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */
	public String openNext() {
		editable = "false";
		Msg.create(cz.getString("info"),cz.getString("checkIt"),FacesMessage.SEVERITY_INFO,true);
		return "open?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */
	public String openPrev() {
		editable = "true";
		Msg.create(cz.getString("info"),cz.getString("fillIt"),FacesMessage.SEVERITY_INFO,true);
		return "open?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */
	public String open() {
		if(view.getSelected().size()==0) {
			Msg.create(cz.getString("warning"),cz.getString("youMustSelectSomething"),FacesMessage.SEVERITY_WARN,false);
			return "";
		}
		view.reload();
		String result = func.checkIfLocked(view.getEdited());
		if (!result.equals("No")) {
			Msg.create(cz.getString("error"),cz.getString("isLockedBy")+" "+result+".",FacesMessage.SEVERITY_WARN,false);
			return "";
		}
		if (func.checkIfOpened(view.getEdited())) {
			Msg.create(cz.getString("warning"),cz.getString("alreadyOpenedKit"),FacesMessage.SEVERITY_WARN,false);
			return "";
		}
		view.lock();
		for(Kit k: view.getEdited()){
			k.setOpened(new Date());
		}
		editable = "true";
		Msg.create(cz.getString("info"),cz.getString("fillIt"),FacesMessage.SEVERITY_INFO,true);
		return "open?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */
	public String consumeNext() {
		editable = "false";
		Msg.create(cz.getString("info"),cz.getString("fillIt"),FacesMessage.SEVERITY_INFO,false);
		return "consume?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */
	public String consumePrev() {
		editable = "true";
		Msg.create(cz.getString("info"),cz.getString("checkIt"),FacesMessage.SEVERITY_INFO,false);
		return "consume?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */
	public String consume() {
		if(view.getSelected().size()==0) {
			Msg.create(cz.getString("warning"),cz.getString("youMustSelectSomething"),FacesMessage.SEVERITY_WARN,false);
			return "";
		}
		view.reload();
		String result = func.checkIfLocked(view.getEdited());
		if (!result.equals("No")) {
			Msg.create(cz.getString("error"),cz.getString("isLockedBy")+" "+result+".",FacesMessage.SEVERITY_WARN,false);
			return "";
		}
		if (!func.checkIfConsumed(view.getEdited())) {
			Msg.create(cz.getString("warning"),cz.getString("alreadyConsumedKit"),FacesMessage.SEVERITY_WARN,false);
			return "";
		}
		view.lock();
		for(Kit k: view.getEdited()){
			k.setConsumed(new Date());
			k.setDiscardReason("Spotřebováno");
		}
		editable = "true";
		Msg.create(cz.getString("info"),cz.getString("fillIt"),FacesMessage.SEVERITY_INFO,true);
		return "consume?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */
	public String update() {
		view.update();
		Msg.create(cz.getString("saved"),"",FacesMessage.SEVERITY_INFO,true);
		return "kit?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */	
	public String add() {
		add = new ArrayList<>();
		add.add(new KitsAdd());
		Msg.create(cz.getString("info"),cz.getString("fillIt"),FacesMessage.SEVERITY_INFO,true);
		return "add?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */	
	public String addRow() {
		add.add(new KitsAdd());
		Msg.create(cz.getString("rowAdded"),"",FacesMessage.SEVERITY_INFO,true);
		return "add?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */	
	public String addSpecific() {
		if (add == null) {
			return "kit?faces-redirect=true";
		}
		view.setEdited(new ArrayList<>());
		for (KitsAdd item : add) {
			for (int i = 0; i < item.getCountOfKits(); i++) {
				view.getEdited().add(new Kit(item));
			}
		}
		editable = "true";
		Msg.create(cz.getString("fillIt"),"",FacesMessage.SEVERITY_INFO,true);
		return "addSpecific?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */	
	public String addNext() {
		editable = "false";
		Msg.create(cz.getString("checkIt"),"",FacesMessage.SEVERITY_INFO,true);
		return "addSpecific?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */
	public String addPrev() {
		if(editable.equals("true")){
			Msg.create(cz.getString("fillIt"),"",FacesMessage.SEVERITY_INFO,true);
			return "add?faces-redirect=true";
		}
		else{
			editable = "true";
			Msg.create(cz.getString("fillSpecific"),"",FacesMessage.SEVERITY_INFO,true);
			RequestContext.getCurrentInstance().update("kitEdit:table");
			return "";
		}
	}
	/* ------------------------------------------------------------------------- */
	public String save() {
		add.clear();
		view.save();
		Msg.create(cz.getString("saved"),"",FacesMessage.SEVERITY_INFO,true);
		return "kit?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */	
	public String cancel() {
		view.unlock();
		Msg.create(cz.getString("unlocked"),"",FacesMessage.SEVERITY_INFO,true);
		return "kit?faces-redirect=true";
	}
	/* ------------------------------------------------------------------------- */
	public void showAll() throws DbIOException{
		if(!showConsumed){
			showConsumed = true;
			view.initAll();
			Msg.create(cz.getString("info"),cz.getString("consumedIsShowed"),FacesMessage.SEVERITY_INFO,false);
		}
		else{
			showConsumed = false;
			view.initCurrent();
			Msg.create(cz.getString("info"),cz.getString("consumedIsHidden"),FacesMessage.SEVERITY_INFO,false);
		}
		RequestContext.getCurrentInstance().update("kit:table");
	}
	/* ------------------------------------------------------------------------- */
	private List discardOptions;
	public List getDiscardOptions() throws DbIOException{
		if(discardOptions==null) {

src/main/webapp/pages/kits/add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<h:outputStylesheet name="css/table.css"/>	

<h:head>
	<title><h:outputText value="#{cz.add}" /> | <h:outputText value="#{cz.kits}" /></title>
</h:head>
<h:body>
	<ui:include src="/pages/menu/menu.xhtml" />

	<h:form rendered="#{loginBean.securityCheck('3') eq true}">
		
		<p:dataTable 	var="item"
						value="#{kitBean.kitAdd}"
						editMode="cell"
						editable="true"
						styleClass="table">
						
			<f:facet name="header">
           		<h:outputText value="#{cz.addKits}" />
       		</f:facet>		 
			
			<p:column headerText="#{cz.type}">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.type}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{item.type}" >
							<f:validateLength maximum="40" /> 
						</p:inputText>	
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.batch}">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.batch}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{item.batch}" >
							<f:validateLength maximum="40" /> 
						</p:inputText>	
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.countOfKits}">
				<p:cellEditor>
					<f:facet name="output">						
						<h:outputText value="#{item.countOfKits}"/>
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{item.countOfKits}"  >
							<f:validateDoubleRange minimum="0" maximum="10" />
						</p:inputText>	
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.expiration}">
				<p:cellEditor>
					<f:facet name="output">	
						<h:outputText value="#{item.expiration}"/>
					</f:facet>
					<f:facet name="input">
						<p:inputMask value="#{item.expiration}" mask="#{cz.dateMask}"/>
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.arriveToLab}">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.arriveToLab}"/>
					</f:facet>
					<f:facet name="input">
						<p:inputMask value="#{item.arriveToLab}" mask="#{cz.dateMask}"/>
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.validation}">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.validation}"/>
					</f:facet>
					<f:facet name="input">
						<p:inputMask value="#{item.validation}" mask="#{cz.dateMask}"/>
					</f:facet>
				</p:cellEditor>
			</p:column>

			<f:facet name="footer">
				<ui:include src="/resources/dialogs/cancel.xhtml" />
				<p:commandButton value="#{cz.addRow}" action="#{kitBean.addRow}"/>
				<p:commandButton value="#{cz.next}" action="#{kitBean.addSpecific}"/>
			</f:facet>
		</p:dataTable>
	</h:form>
	<h:form id="securityAlert" rendered="#{loginBean.securityCheck('3') eq false}">
		<ui:include src="/pages/expired.xhtml" />
	</h:form>
</h:body>
</html>

src/main/webapp/pages/kits/addSpecific.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	<h:outputStylesheet name="css/table.css"/>
<h:head>
	<title><h:outputText value="#{cz.add}" /> | <h:outputText value="#{cz.kits}" /></title>
</h:head>
<h:body>
	<ui:include src="/pages/menu/menu.xhtml" />
	
	<h:form rendered="#{loginBean.securityCheck('3') eq true}">
		<p:dataTable 	id="addSpecific"
						var="item"
						value="#{kitBean.view.edited}"
						editMode="cell"
						rowKey="item.id"
						editable="#{kitBean.editable}" 
						styleClass="table">
						
			<f:facet name="header">
           		<h:outputText value="#{cz.add}" />
       		</f:facet>
       		
			<p:column headerText="#{cz.type}" toggleable="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.type}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{item.type}"  >
							<f:validateLength minimum="3" maximum="40" /> 
						</p:inputText>	
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.intId}" visible="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.internalId}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{item.internalId}" >
							<f:validateLength maximum="40" /> 
						</p:inputText>	
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.batch}" toggleable="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.batch}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{item.batch}" >
							<f:validateLength minimum="3" maximum="40" /> 
						</p:inputText>	
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.expiration}" toggleable="false">
				<p:cellEditor>
					<f:facet name="output">	
						<h:outputText value="#{item.expiration}" />
					</f:facet>
					<f:facet name="input">
						<p:inputMask value="#{item.expiration}" mask="#{cz.dateMask}"/>
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.arriveToLab}">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.arriveToLab}" />
					</f:facet>
					<f:facet name="input">
						<p:inputMask value="#{item.arriveToLab}" mask="#{cz.dateMask}" />
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.validation}" toggleable="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.validation}" />
					</f:facet>
					<f:facet name="input">
						<p:inputMask value="#{item.validation}" mask="#{cz.dateMask}"/>
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.revalidation}" visible="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.revalidation}" />
					</f:facet>
					<f:facet name="input">
						<p:inputMask value="#{item.revalidation}" mask="#{cz.dateMask}" />				
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.newExpiration}" visible="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.newExpiration}" />
					</f:facet>
					<f:facet name="input">
						<p:inputMask value="#{item.newExpiration}" mask="#{cz.dateMask}" />				
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.manual}" visible="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.manual}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{item.manual}" >
							<f:validateLength maximum="40" /> 
						</p:inputText>	
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.note}" visible="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.note}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{item.note}" >
							<f:validateLength maximum="40" /> 
						</p:inputText>	
					</f:facet>
				</p:cellEditor>
			</p:column>			
		
			<f:facet name="footer">
				<p:commandButton id="toggler" type="button" value="#{cz.showColumns}" icon="ui-icon-calculator" style="float: left"/>
		        <p:columnToggler datasource="addSpecific" trigger="toggler" /> 
				<ui:include src="/resources/dialogs/cancel.xhtml" />
				<p:commandButton value="#{cz.prev}" action="#{kitBean.addPrev}" />
				<p:commandButton value="#{cz.done}" action="#{kitBean.save}" rendered="#{kitBean.editable eq 'false'}"/>
				<p:commandButton value="#{cz.next}" action="#{kitBean.addNext}" rendered="#{kitBean.editable eq 'true'}"/>
			</f:facet>

		</p:dataTable>

	</h:form>
	<h:form id="securityAlert" rendered="#{loginBean.securityCheck('3') eq false}">
		<ui:include src="/pages/expired.xhtml" />
	</h:form>
</h:body>
</html>

src/main/webapp/pages/kits/consume.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html 	xmlns="http://www.w3.org/1999/xhtml"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:p="http://primefaces.org/ui"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:ui="http://java.sun.com/jsf/facelets">
	<h:outputStylesheet name="css/table.css"/>
<h:head>
	<title><h:outputText value="#{cz.consume}" /> | <h:outputText value="#{cz.kits}" /></title>
</h:head> 
<h:body>
	<ui:include src="/pages/menu/menu.xhtml" />
	
	<h:form rendered="#{loginBean.securityCheck('3') eq true}">
		<p:dataTable 	id="consume"
						var="item"
						value="#{kitBean.view.edited}"
						editMode="cell"
						rowKey="item.id"
						editable="#{kitBean.editable}" 
						styleClass="table">
						
			<f:facet name="header">
           		<h:outputText value="#{cz.consume}" />
       		</f:facet>
       		
			<p:column headerText="#{cz.type}" toggleable="false" editable="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.type}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{item.type}" />
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.intId}" visible="false" editable="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.internalId}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{item.internalId}"/>
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.batch}" toggleable="false" editable="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.batch}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{item.batch}" />
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.consumed}" toggleable="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.consumed}" />
					</f:facet>
					<f:facet name="input">
						<p:inputMask value="#{item.consumed}" mask="#{cz.dateMask}" />	
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.discardReason}" toggleable="false">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.discardReason}"/>
					</f:facet>
					<f:facet name="input">
						<p:selectOneMenu  value="#{item.discardReason}">
            				<f:selectItems value="#{kitBean.discardOptions}" />
        				</p:selectOneMenu>
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="#{cz.note}" >
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{item.note}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{item.note}" />
					</f:facet>
				</p:cellEditor>
			</p:column>			
		
			<f:facet name="footer">
				<p:commandButton id="toggler" type="button" value="#{cz.showColumns}" icon="ui-icon-calculator" style="float: left"/>
		        <p:columnToggler datasource="consume" trigger="toggler" /> 
				<ui:include src="/resources/dialogs/cancel.xhtml" />
				<p:commandButton value="#{cz.prev}" action="#{kitBean.consumePrev}" rendered="#{kitBean.editable eq 'false'}"/>
				<p:commandButton value="#{cz.done}" action="#{kitBean.update}" rendered="#{kitBean.editable eq 'false'}"/>
				<p:commandButton value="#{cz.next}" action="#{kitBean.consumeNext}" rendered="#{kitBean.editable eq 'true'}"/>
			</f:facet>  

		</p:dataTable>

	</h:form>
	<h:form id="securityAlert" rendered="#{loginBean.securityCheck('3') eq false}">
		<ui:include src="/pages/expired.xhtml" />
	</h:form>
</h:body>
</html>